package group

import (
	"crypto/rand"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"
)

// Room is a multi-peer chat room secured by a shared symmetric group key.
// The key is generated by the creator and distributed to members over
// existing pairwise E2E sessions (never in plaintext on the wire).
// v1 note: removing a member does not rotate the key automatically;
// the creator should run rekey (new key + invite remaining members).
type Room struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Creator   string    `json:"creator_jid"`
	Key       []byte    `json:"key"`
	Members   []string  `json:"members"`
	CreatedAt time.Time `json:"created_at"`
}

// Store persists rooms in a JSON file.
type Store struct {
	path  string
	mu    sync.RWMutex
	rooms map[string]*Room // key: room ID
}

// New creates or loads a store.
func New(path string) (*Store, error) {
	s := &Store{path: path, rooms: make(map[string]*Room)}
	if data, err := os.ReadFile(path); err == nil {
		var stored struct {
			Rooms []*Room `json:"rooms"`
		}
		if err := json.Unmarshal(data, &stored); err != nil {
			return nil, fmt.Errorf("invalid group store: %w", err)
		}
		for _, r := range stored.Rooms {
			if r != nil && r.ID != "" {
				s.rooms[r.ID] = r
			}
		}
	} else if !os.IsNotExist(err) {
		return nil, err
	}
	return s, nil
}

// Create generates a room with a fresh random 32-byte key.
func (s *Store) Create(name, creatorJID string) (*Room, error) {
	if name == "" {
		return nil, fmt.Errorf("room name must not be empty")
	}
	key := make([]byte, 32)
	if _, err := rand.Read(key); err != nil {
		return nil, err
	}
	idBytes := make([]byte, 8)
	if _, err := rand.Read(idBytes); err != nil {
		return nil, err
	}
	room := &Room{
		ID:        fmt.Sprintf("grp-%x", idBytes),
		Name:      name,
		Creator:   creatorJID,
		Key:       key,
		Members:   []string{creatorJID},
		CreatedAt: time.Now(),
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.rooms[room.ID] = room
	return room, s.saveLocked()
}

// Add inserts a room learned via invite (or re-adds after rekey).
func (s *Store) Add(room *Room) error {
	if room == nil || room.ID == "" || len(room.Key) != 32 {
		return fmt.Errorf("invalid room payload")
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.rooms[room.ID] = room
	return s.saveLocked()
}

// Get returns a room by full ID or unique prefix.
func (s *Store) Get(idOrPrefix string) (*Room, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	if r, ok := s.rooms[idOrPrefix]; ok {
		return r, true
	}
	var match *Room
	for id, r := range s.rooms {
		if len(idOrPrefix) >= 4 && len(id) >= len(idOrPrefix) && id[:len(idOrPrefix)] == idOrPrefix {
			if match != nil {
				return nil, false // ambiguous prefix
			}
			match = r
		}
	}
	if match == nil {
		return nil, false
	}
	return match, true
}

// GetByName returns the first room with the given name.
func (s *Store) GetByName(name string) (*Room, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	for _, r := range s.rooms {
		if r.Name == name {
			return r, true
		}
	}
	return nil, false
}

// Resolve accepts an ID, unique prefix, or name.
func (s *Store) Resolve(ref string) (*Room, bool) {
	if r, ok := s.Get(ref); ok {
		return r, true
	}
	return s.GetByName(ref)
}

// List returns all rooms sorted by creation time.
func (s *Store) List() []*Room {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]*Room, 0, len(s.rooms))
	for _, r := range s.rooms {
		out = append(out, r)
	}
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j].CreatedAt.Before(out[j-1].CreatedAt); j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}

// AddMember adds a JID idempotently.
func (s *Store) AddMember(roomID, jid string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	r, ok := s.rooms[roomID]
	if !ok {
		return fmt.Errorf("unknown room %s", roomID)
	}
	for _, m := range r.Members {
		if m == jid {
			return nil
		}
	}
	r.Members = append(r.Members, jid)
	return s.saveLocked()
}

// RemoveMember removes a JID; rooms are kept even when empty (leave = local).
func (s *Store) RemoveMember(roomID, jid string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	r, ok := s.rooms[roomID]
	if !ok {
		return fmt.Errorf("unknown room %s", roomID)
	}
	kept := r.Members[:0]
	for _, m := range r.Members {
		if m != jid {
			kept = append(kept, m)
		}
	}
	r.Members = kept
	return s.saveLocked()
}

// IsMember reports membership.
func (s *Store) IsMember(roomID, jid string) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	r, ok := s.rooms[roomID]
	if !ok {
		return false
	}
	for _, m := range r.Members {
		if m == jid {
			return true
		}
	}
	return false
}

// Rekey rotates the room key; caller must invite remaining members afterwards.
func (s *Store) Rekey(roomID string) (*Room, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	r, ok := s.rooms[roomID]
	if !ok {
		return nil, fmt.Errorf("unknown room %s", roomID)
	}
	key := make([]byte, 32)
	if _, err := rand.Read(key); err != nil {
		return nil, err
	}
	r.Key = key
	return r, s.saveLocked()
}

func (s *Store) saveLocked() error {
	if err := os.MkdirAll(filepath.Dir(s.path), 0o700); err != nil {
		return err
	}
	rooms := make([]*Room, 0, len(s.rooms))
	for _, r := range s.rooms {
		rooms = append(rooms, r)
	}
	data, err := json.Marshal(struct {
		Rooms []*Room `json:"rooms"`
	}{Rooms: rooms})
	if err != nil {
		return err
	}
	return os.WriteFile(s.path, data, 0o600)
}

// DefaultGroupsPath returns the default store location.
func DefaultGroupsPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		home = "."
	}
	return filepath.Join(home, ".korik", "groups.json")
}
